export enum CrudEnum {
	DELETE = 'DELETE',
	UPDATE = 'UPDATE'
}

export enum SubscriptionTypesEnum {
	NEW_MESSAGE = 'NEW_MESSAGE',
	FILE_UPLOADED = 'FILE_UPLOADED',
	MESSAGE_DELETED = 'MESSAGE_DELETED',
	MESSAGE_EDITED = 'MESSAGE_EDITED',
	UPDATE_TYPING_USERS = 'UPDATE_TYPING_USERS',
	UPDATE_ACTIVE_USERS = 'UPDATE_ACTIVE_USERS',
	USER_MENTIONED = 'USER_MENTIONED'
}

export enum UserUpdatesEnum {
	NEW_NOTIFICATION = 'NEW_NOTIFICATION'
}

export enum ApolloTypesEnum {
	MESSAGE = 'Message',
	MESSAGE_EDGE = 'MessageEdge',
	MESSAGE_CREATED_BY = 'CreatedBy',
	PAGE_INFO = 'PageInfo',
	MESSAGE_CONNECTION = 'MessageConnection'
}
