version: "3"
services:
  chatty-backend:
    container_name: chatty-backend
    build: ./
    volumes:
      - ./:/usr/src/chatty-backend
    command: npm start
    working_dir: /usr/src/chatty-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  mongo:
    image: mongo:bionic
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - ./db:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    command:
      redis-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

