export const SET_AUTH_MODAL = 'SET_AUTH_MODAL';
export const RESET_MODALS = 'RESET_MODALS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_GENERIC_MODAL = 'SET_GENERIC_MODAL';
export const SET_CHAT_SLUG = 'SET_CHAT_SLUG';
export const SET_TYPING_USERS = 'SET_TYPING_USERS';
export const SET_MENTION_SUGGESTER = 'SET_MENTION_SUGGESTER';
export const SET_NOTIFICATIONS_DATA = 'SET_NOTIFICATIONS_DATA';
